### ISSUE TITLE
Plausible misuse of the Minkowski space terminology?

### ISSUE THREAD

**Issue by tommai78101** [kroitor/gjk.c#1]
Thanks again for such a wonderful Readme.md you have done. I've shared your repository with others, and they did give some feedback. I am wondering if you're able to answer them.

One of them said the following:

> I'm not sure why you feel the need for Minkowski-Space. Surely R^n suffices and if I'm any judge that is what you use. Please note that M^n and R^n are not the same thing. In fact, I can't see why Minkowski-Space is really used here.

The GJK algorithm relies on Minkowski sums + differences, which transforms the problem into a space sometimes called the collision space - what he calls the Minkowski space. [Source](https://www.haroldserrano.com/blog/visualizing-the-gjk-collision-algorithm)

Perhaps, it could be that there may be some sort of mixup between the Minkowski space mentioned in the Readme.md, and the Minkowski space related to physics.

**Comment by kroitor** [comment]
Yeah, you are right, that space is called `Minkowski space` just for explanation purposes. Basically, most articles and videos explaining GJK will refer to Minkowski space in some form. 

The Minkowski space from the Readme does not relate to a scientifically-precise definition of Minkowski space. I would say, that's a Minkowski space for non-physicians, for common people, and for use in everyday life ;) I didn't think the name would really matter for most readers, it is mentioned just a few times to refer to that surreal intersection space described in the article.

The article itself does not pretend to be a scientific work, of course, it's an introductory material for those who are interested to learn more about it. I had difficulties grasping it on my own, not having a human-readable explanation of how it works, therefore I decided to make one  in very simple terms for others, who might need it as well.

**Comment by kroitor** [comment]
Thank you very much for sharing it, and for the feedback as well! Really appreciate it!
