### ISSUE TITLE
Downloading the package

### ISSUE THREAD

**Issue by zouhair0** [kroitor/gjk.c#7]
Hello,
How can i download your package in python3?
I downloaded the files: gjk.c   gjk_wrapper.c     and    setup.py, then when i do the command:  python setup.py build it creates a file gjk.cpython-35m-x86_64-linux-gnu.so in  build folder....
What i should do after ?

**Comment by kroitor** [comment]
Hi, @zouhair0 !

After you have the `.so` file, just put it somewhere in the same folder where your other python scripts are. You can then use it by importing it just like you would do with a normal "source" module, Python finds compiled binary modules automatically for you. So, if you place the `.so` file in a folder then you can `import gjk` there, see [test.py](https://github.com/kroitor/gjk.c/blob/master/python/test.py):

```
import unittest
import gjk

class TestGjk(unittest.TestCase):

    def test_main(self):
        vertices1 = ((4,11), (4,5), (9,9))
        vertices2 = ((5,7), (7,3), (10,2), (12, 7))
        self.assertTrue(gjk.gjk(vertices1, vertices2))

    def test_empty(self):
        vertices1 = ()
        vertices2 = ((5,7), (7,3), (10,2), (12, 7))
        self.assertFalse(gjk.gjk(vertices1, vertices2))

    def test_mixed(self):
        vertices1 = ([4.0,11], (4,5), (9,9))
        vertices2 = [(5,7), (7.1,3), (10,2), (12, 7)]
        self.assertTrue(gjk.gjk(vertices1, vertices2))

    def test_bad_argument_type(self):
        with self.assertRaises(TypeError):
            gjk.gjk(None, None)

    def test_bad_argument_item(self):
        vertices1 = ((None,11),)
        vertices2 = ()
        vertices3 = ((11,),)

        with self.assertRaises(TypeError):
            gjk.gjk(vertices1, vertices2)

        with self.assertRaises(TypeError):
            gjk.gjk(vertices1, vertices3)


if __name__ == '__main__':
    unittest.main()
```

Let me know if it helped you or not. Thx!

**Comment by zouhair0** [comment]
OK. Thank you.
I have a question please...
What i understand, is that gjk.gjk(vertices1, vertices2) return 1 if the two shapes(vertices1 and vertices2) collided and 0 if  not.  
So, i did this test for two segments who are normaly collided: 
def test(self): 
        vertices1=((1,0),(6,0))
        vertices2=((3,0),(8,0))
        self.assertTrue(gjk.gjk(vertices1, vertices2))
But the test failed...!!

**Comment by kroitor** [comment]
@zouhair0 but... you're using shapes of two points, which are not *"intersectable"*. You need each shape to have at least three points (to be a 2D-shape), otherwise your shapes are lines of two points.
